name: Publish Site

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.x
      USER: ${{ github.repository_owner }}
      # REPO_NAME: ${{ github.event.repository.name }}
      REPO: ${{ secrets.REPO }}

    steps:
      - name: Checkout site
        uses: actions/checkout@v6

      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ env.REPO }}

      - name: Checkout data
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO }}
          token: ${{ steps.app-token.outputs.token }}
          path: ${{ env.REPO }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build Site
        run: cd ${{ env.REPO }} && bash deploy.sh data/data.json

      - name: Setup pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v5
